### ISSUE TITLE
lsub backbox

### ISSUE THREAD

**Issue by hakimarx** [elelement/Meizu-M2-ROOT-tips#1]
1. i cant run lsub command (you write in readme "lsub"). i can run lsusb.
root@a-X201EP:/home/a/.android# lsub
No command 'lsub' found, did you mean:
 Command 'lsusb' from package 'usbutils' (main)
 Command 'qsub' from package 'slurm-llnl-torque' (universe)
 Command 'qsub' from package 'torque-client-x11' (universe)
 Command 'qsub' from package 'torque-client' (universe)
 Command 'qsub' from package 'gridengine-client' (universe)
lsub: command not found

2. and "udev" command cannot run. i can run with : sudo /etc/init.d/udev restart 
root@a-X201EP:/home/a/.android# udev restart
No command 'udev' found, did you mean:
 Command 'udevd' from package 'udev' (main)
 Command 'udav' from package 'udav' (universe)
 Command 'udv' from package 'ncbi-tools-x11' (universe)
udev: command not found

3. ~ $ sh /sdcard/unlock_bootloader.sh 
wc: /dev/block/platform/mtk-msdc.0/by-name/frp: Permission denied
FRP not found, or FRP length is invalid

**Comment by elelement** [comment]
- "lsusb": It's a typing error, thanks.
- "udev": you may need either to install the package, or to create an alias.
- "bootloader": did you tried to run the command as root user?

**Comment by hakimarx** [comment]
"bootloader": i can't acces root.
i cannot downgrade to flyme 4.54.l. i've put update.zip to internal and update via file manager then restart, but my phone just reboot. Not entering to recovery, because my recovery lost
before this, i install nethunter kali, and unchroot.  and i was install busybox to /sytem/bin. since this ,the trouble began.
How to re-root again, after uninstall kingroot, i can get root anymore..Kingroot not work, just 70 % then end. my stock recovery lost too. Help!
im not install TWRP and not unlock bootloader before. flash recovery need root acces. now i dont have root acces to flash with rashr/flashify. i have change kingroot with super su script (sh /sdcard/mrw/root.sh) <a href='https://postimg.org/image/48d7g67uf/' target='_blank'><img src='https://s15.postimg.org/48d7g67uf/18664652_10213123925477344_3142579603037891508_n.jpg' border='0' alt='postimage'/></a>
when i uninstall kingroot, and run terminal android sh /sdcard/mrw/root.sh, it appear like this:

```
/ $ su
/ $ sudo su
/system/bin/sh: sudo: not found
/ $ sh /sdcard/mrw/root.sh
---------------------------------------
---------- Made By : Mr.W0lf ----------
---- Thanks @Chainfire for SuperSU ----
---------------------------------------
mount: mounting /dev/block/platform/mtk-msdc.0/by-name/system on /system failed: Permission denied
java.lang.SecurityException: Permission Denial: killBackgroundProcesses() from pid=6402, uid=10067 requires android.permission.KILL_BACKGROUND_PROCESSES
        at android.os.Parcel.readException(Parcel.java:1546)        at android.os.Parcel.readException(Parcel.java:1499)        at android.app.ActivityManagerProxy.killBackgroundProcesses(ActivityManagerNative.java:4427)
        at com.android.commands.am.Am.runKill(Am.java:884)
        at com.android.commands.am.Am.onRun(Am.java:313)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:97)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
Failure - not installed for 0
java.lang.SecurityException: Permission Denial: killBackgroundProcesses() from pid=6440, uid=10067 requires android.permission.KILL_BACKGROUND_PROCESSES
        at android.os.Parcel.readException(Parcel.java:1546)        at android.os.Parcel.readException(Parcel.java:1499)        at android.app.ActivityManagerProxy.killBackgroundProcesses(ActivityManagerNative.java:4427)
        at com.android.commands.am.Am.runKill(Am.java:884)
        at com.android.commands.am.Am.onRun(Am.java:313)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:97)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
Failure - not installed for 0
rm: can't remove '/system/app/Kinguser.apk': No such file or directory
rm: can't remove '/system/app/Kinguser': No such file or directory
java.lang.SecurityException: Permission Denial: killBackgroundProcesses() from pid=6471, uid=10067 requires android.permission.KILL_BACKGROUND_PROCESSES
        at android.os.Parcel.readException(Parcel.java:1546)        at android.os.Parcel.readException(Parcel.java:1499)        at android.app.ActivityManagerProxy.killBackgroundProcesses(ActivityManagerNative.java:4427)
        at com.android.commands.am.Am.runKill(Am.java:884)
        at com.android.commands.am.Am.onRun(Am.java:313)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:97)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
Failure - not installed for 0
/sdcard/mrw/root.sh: line 17: can't create /system/bin/busybox: Read-only file system
chown: /system/bin/busybox: Read-only file system
chmod: /system/bin/busybox: Read-only file system
chattr: setting flags on /system/xbin/ku.sud: Permission denied
rm: remove '/system/xbin/ku.sud'?
chattr: setting flags on /system/xbin/su: Permission denied
rm: remove '/system/xbin/su'?
chattr: setting flags on /system/xbin/supolicy: Permission denied
rm: remove '/system/xbin/supolicy'?
/sdcard/mrw/root.sh: line 30: can't create /system/xbin/su: Read-only file system
/sdcard/mrw/root.sh: line 31: can't create /system/xbin/daemonsu: Read-only file system
/sdcard/mrw/root.sh: line 32: can't create /system/xbin/sugote: Read-only file system
/sdcard/mrw/root.sh: line 33: can't create /system/xbin/sugote-mksh: Read-only file system
chown: /system/xbin/su: Read-only file system
chmod: /system/xbin/su: Read-only file system
chown: /system/xbin/sugote: Read-only file system
chmod: /system/xbin/sugote: Read-only file system
chown: /system/xbin/sugote-mksh: Read-only file system
chmod: /system/xbin/sugote-mksh: Read-only file system
chown: /system/xbin/daemonsu: Read-only file system
chmod: /system/xbin/daemonsu: Read-only file system
rm: can't remove '/data/data/com.kingroot.RushRoot': No such file or directory
rm: descend into directory '/data/data-lib/com.kingroot.RushRoot'?
rm: can't remove '/data/data/com.kingroot.kinguser': No such file or directory
rm: can't remove '/data/data-lib/com.kingroot.kinguser': No such file or directory
rm: can't remove '/data/data/com.kingroot.master': No such file or directory

chattr: stat /system/bin/.usr/.ku: No such file or directoryrm: can't remove '/system/bin/.usr/.ku': No such file or directory
chattr: stat /system/bin/rt.sh: No such file or directory
rm: can't remove '/system/bin/rt.sh': No such file or directory
chattr: setting flags on /system/bin/su: Permission denied
rm: remove '/system/bin/su'?
chattr: stat /system/bin/ddexe: No such file or directory
rm: can't remove '/system/bin/ddexe': No such file or directory
chattr: stat /system/bin/install-recovery.sh: No such file or directory
rm: can't remove '/system/bin/install-recovery.sh': No such file or directory
chattr: stat /system/bin/install-recovery.sh-ku.bak: No such file or directory
rm: can't remove '/system/bin/install-recovery.sh-ku.bak': No such file or directory`
```
